// Auto-generated by scripts/generate-image-dimensions.ts
// Run: pnpm tsx scripts/generate-image-dimensions.ts

export const imageDimensions: Record<string, { width: number; height: number }> = {
  "/images/portfolio/beyondwords/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/beyondwords/articles.avif": {
    "width": 3200,
    "height": 6400
  },
  "/images/portfolio/beyondwords/beyondwords-ui.avif": {
    "width": 2884,
    "height": 1604
  },
  "/images/portfolio/beyondwords/dashboard.avif": {
    "width": 3200,
    "height": 6800
  },
  "/images/portfolio/beyondwords/homepage-concept.avif": {
    "width": 3200,
    "height": 19784
  },
  "/images/portfolio/beyondwords/onboarding-1.avif": {
    "width": 3200,
    "height": 7200
  },
  "/images/portfolio/beyondwords/onboarding-2.avif": {
    "width": 3200,
    "height": 7200
  },
  "/images/portfolio/beyondwords/plan-management.avif": {
    "width": 3200,
    "height": 6400
  },
  "/images/portfolio/beyondwords/security.avif": {
    "width": 3200,
    "height": 6400
  },
  "/images/portfolio/beyondwords/semantic-colours.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/beyondwords/ui-library-component-details.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/beyondwords/ui-library-usage.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/beyondwords/ui-library.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/booking/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/booking/booking-bg.avif": {
    "width": 2400,
    "height": 1599
  },
  "/images/portfolio/booking/booking-ui-1.avif": {
    "width": 800,
    "height": 1750
  },
  "/images/portfolio/booking/booking-ui-2.avif": {
    "width": 800,
    "height": 1750
  },
  "/images/portfolio/booking/booking-ui-3.avif": {
    "width": 800,
    "height": 1750
  },
  "/images/portfolio/booking/booking-ui-4.avif": {
    "width": 800,
    "height": 1750
  },
  "/images/portfolio/booking/bookingcom-4.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/booking/design-workshop.avif": {
    "width": 1230,
    "height": 228
  },
  "/images/portfolio/booking/payment-modal.avif": {
    "width": 3360,
    "height": 1863
  },
  "/images/portfolio/booking/payment-presentation.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/booking/payment-prototype.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/booking/payment-vision.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/booking/user-testing-report.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/boston-north-end/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/boston-north-end/ar-1.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/boston-north-end/ar-2.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/boston-north-end/hero.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/boston-north-end/map.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/boston-north-end/north-square.avif": {
    "width": 2044,
    "height": 1150
  },
  "/images/portfolio/boston-north-end/north-square.webp": {
    "width": 2044,
    "height": 1150
  },
  "/images/portfolio/boston-north-end/story.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/boston-north-end/write.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/brokerengine/5tHNIK8Ki1uZHAWwcz5rp7UUZ0.avif": {
    "width": 914,
    "height": 526
  },
  "/images/portfolio/brokerengine/_brokerengine-bg-poster.avif": {
    "width": 598,
    "height": 400
  },
  "/images/portfolio/brokerengine/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/brokerengine/brokerengine-ui.avif": {
    "width": 2880,
    "height": 1600
  },
  "/images/portfolio/brokerengine/card-payment-system.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/brokerengine/comments.avif": {
    "width": 3476,
    "height": 2226
  },
  "/images/portfolio/brokerengine/compose-component.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/brokerengine/deal-after.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/brokerengine/deal-before.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/brokerengine/deals-after.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/brokerengine/deals-before.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/brokerengine/figma-files.avif": {
    "width": 6080,
    "height": 2116
  },
  "/images/portfolio/brokerengine/filter-after.avif": {
    "width": 3200,
    "height": 3704
  },
  "/images/portfolio/brokerengine/filter-before.avif": {
    "width": 3200,
    "height": 3704
  },
  "/images/portfolio/brokerengine/messaging.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/brokerengine/onboarding.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/brokerengine/pipeline.avif": {
    "width": 2880,
    "height": 1600
  },
  "/images/portfolio/brokerengine/responsive-contact.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/brokerengine/tasks.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/cosmitto/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/cosmitto/booking-confirmation.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/cosmitto/booking-flow.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/cosmitto/course.avif": {
    "width": 3200,
    "height": 9740
  },
  "/images/portfolio/cosmitto/cover.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/cosmitto/portal-cms.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/cosmitto/portal-upgrade.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/cosmitto/provider-portal.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/cosmitto/search-tablet.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/cosmitto/search-tablet.png": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/cosmitto/search.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/creative-ai/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/creative-ai/cover.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/creative-ai/ideaverse-collaborate.avif": {
    "width": 3200,
    "height": 2000
  },
  "/images/portfolio/creative-ai/ideaverse-collect.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/creative-ai/ideaverse-explore.avif": {
    "width": 3200,
    "height": 2000
  },
  "/images/portfolio/creative-ai/ideaverse-finetune.avif": {
    "width": 3200,
    "height": 2000
  },
  "/images/portfolio/creative-ai/ml-images.avif": {
    "width": 3200,
    "height": 3220
  },
  "/images/portfolio/creative-ai/persona-1.avif": {
    "width": 2480,
    "height": 3508
  },
  "/images/portfolio/creative-ai/persona-2.avif": {
    "width": 2480,
    "height": 3508
  },
  "/images/portfolio/creative-ai/persona-3.avif": {
    "width": 2480,
    "height": 3508
  },
  "/images/portfolio/creative-ai/persona-4.avif": {
    "width": 2480,
    "height": 3508
  },
  "/images/portfolio/creative-ai/sketching.avif": {
    "width": 1290,
    "height": 968
  },
  "/images/portfolio/creative-ai/sliders.avif": {
    "width": 3200,
    "height": 4020
  },
  "/images/portfolio/creative-ai/sprint-day-1.avif": {
    "width": 4000,
    "height": 2667
  },
  "/images/portfolio/creative-ai/sprint-day-2.avif": {
    "width": 4000,
    "height": 2569
  },
  "/images/portfolio/creative-ai/style-guide.avif": {
    "width": 3200,
    "height": 4020
  },
  "/images/portfolio/creative-ai/style-transfer.avif": {
    "width": 3200,
    "height": 6060
  },
  "/images/portfolio/creative-ai/team.avif": {
    "width": 890,
    "height": 667
  },
  "/images/portfolio/creative-ai/workshop.avif": {
    "width": 2248,
    "height": 1996
  },
  "/images/portfolio/donotstay/donotstay-1.jpg": {
    "width": 2560,
    "height": 1914
  },
  "/images/portfolio/donotstay/donotstay-poster.avif": {
    "width": 2880,
    "height": 2160
  },
  "/images/portfolio/envato/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/envato/api-shipped.avif": {
    "width": 1600,
    "height": 900
  },
  "/images/portfolio/envato/api-shipped.webp": {
    "width": 1600,
    "height": 900
  },
  "/images/portfolio/envato/design-party.avif": {
    "width": 1400,
    "height": 933
  },
  "/images/portfolio/envato/design-party.webp": {
    "width": 1400,
    "height": 933
  },
  "/images/portfolio/envato/feedback-dot-voting.avif": {
    "width": 1400,
    "height": 788
  },
  "/images/portfolio/envato/layers-outcome.avif": {
    "width": 2000,
    "height": 1116
  },
  "/images/portfolio/envato/layers-outcome.webp": {
    "width": 2000,
    "height": 1116
  },
  "/images/portfolio/envato/sprint-ideas.avif": {
    "width": 960,
    "height": 540
  },
  "/images/portfolio/envato/sprint-ideas.webp": {
    "width": 960,
    "height": 540
  },
  "/images/portfolio/envato/sprint-war-room.avif": {
    "width": 4800,
    "height": 1070
  },
  "/images/portfolio/envato/sprint-wireframes.avif": {
    "width": 960,
    "height": 540
  },
  "/images/portfolio/envato/unstock.avif": {
    "width": 2000,
    "height": 2000
  },
  "/images/portfolio/gsq/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/gsq/faceted-search.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/gsq/gsq-bg.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/gsq/gsq-ui-desktop.avif": {
    "width": 2800,
    "height": 2000
  },
  "/images/portfolio/gsq/gsq-ui-modal.avif": {
    "width": 2720,
    "height": 1600
  },
  "/images/portfolio/gsq/hero.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/gsq/portal-1.avif": {
    "width": 3200,
    "height": 2000
  },
  "/images/portfolio/gsq/portal-2.avif": {
    "width": 3200,
    "height": 2000
  },
  "/images/portfolio/harvard/athena-1.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/athena-2.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/athena-3.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/blenheim-scan-1.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/harvard/blenheim-scan-2.avif": {
    "width": 1920,
    "height": 1080
  },
  "/images/portfolio/harvard/blenheim-scan-3.avif": {
    "width": 1920,
    "height": 1080
  },
  "/images/portfolio/harvard/blenheim-scan-4.avif": {
    "width": 1920,
    "height": 1080
  },
  "/images/portfolio/harvard/blenheim-story.avif": {
    "width": 4000,
    "height": 2400
  },
  "/images/portfolio/harvard/blenheim-xray.avif": {
    "width": 4000,
    "height": 2400
  },
  "/images/portfolio/harvard/giza-360.avif": {
    "width": 2048,
    "height": 1280
  },
  "/images/portfolio/harvard/giza-concepts.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/giza-hero.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/harvard/library-gutenberg.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/library-map.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/library-wayfinding.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/library-widener.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/new-alexandria-commentary.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/harvard/new-alexandria-greek.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/harvard/new-alexandria-hero.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/harvard/new-alexandria-search.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/harvard/new-alexandria-split.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/harvard/parthenon-3d.avif": {
    "width": 2000,
    "height": 1125
  },
  "/images/portfolio/harvard/parthenon-annotations.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/parthenon-hero.avif": {
    "width": 2500,
    "height": 1406
  },
  "/images/portfolio/harvard/parthenon-repatriation-1.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/parthenon-repatriation-2.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/parthenon-repatriation-3.avif": {
    "width": 4000,
    "height": 2250
  },
  "/images/portfolio/harvard/parthenon-wayfinding.avif": {
    "width": 2000,
    "height": 1125
  },
  "/images/portfolio/krakatoa/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/krakatoa/background.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/krakatoa/background.png": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/krakatoa/breakpoints.avif": {
    "width": 2758,
    "height": 1942
  },
  "/images/portfolio/krakatoa/cart.avif": {
    "width": 2400,
    "height": 1800
  },
  "/images/portfolio/krakatoa/cover.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/krakatoa/dashboard-1.avif": {
    "width": 3120,
    "height": 4004
  },
  "/images/portfolio/krakatoa/dashboard-2.avif": {
    "width": 3120,
    "height": 1478
  },
  "/images/portfolio/krakatoa/desktop.avif": {
    "width": 2800,
    "height": 2000
  },
  "/images/portfolio/krakatoa/desktop.png": {
    "width": 2800,
    "height": 2000
  },
  "/images/portfolio/krakatoa/faceted-search.avif": {
    "width": 2400,
    "height": 1800
  },
  "/images/portfolio/krakatoa/gallery.avif": {
    "width": 2400,
    "height": 1800
  },
  "/images/portfolio/krakatoa/handoff.avif": {
    "width": 2242,
    "height": 2218
  },
  "/images/portfolio/krakatoa/mega-menu.avif": {
    "width": 2340,
    "height": 1500
  },
  "/images/portfolio/krakatoa/metadata.avif": {
    "width": 3218,
    "height": 2920
  },
  "/images/portfolio/krakatoa/midjourney-art.avif": {
    "width": 3312,
    "height": 3505
  },
  "/images/portfolio/krakatoa/mobile.avif": {
    "width": 640,
    "height": 1600
  },
  "/images/portfolio/krakatoa/mobile.png": {
    "width": 640,
    "height": 1600
  },
  "/images/portfolio/nametag/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/nametag/auth-options.avif": {
    "width": 3476,
    "height": 2226
  },
  "/images/portfolio/nametag/claim-box.avif": {
    "width": 2992,
    "height": 1868
  },
  "/images/portfolio/nametag/ds-components.avif": {
    "width": 3476,
    "height": 2226
  },
  "/images/portfolio/nametag/extension.avif": {
    "width": 3200,
    "height": 7200
  },
  "/images/portfolio/nametag/figma-setup.avif": {
    "width": 1888,
    "height": 1536
  },
  "/images/portfolio/nametag/mobile-concepts-1.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/nametag/mobile-concepts-2.avif": {
    "width": 2252,
    "height": 6496
  },
  "/images/portfolio/nametag/nametag-1.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/nametag/noken-drop.avif": {
    "width": 2992,
    "height": 4345
  },
  "/images/portfolio/nametag/noken-figma.avif": {
    "width": 2992,
    "height": 1868
  },
  "/images/portfolio/nametag/onboarding-1.avif": {
    "width": 2880,
    "height": 1600
  },
  "/images/portfolio/nametag/onboarding-2.avif": {
    "width": 2880,
    "height": 1600
  },
  "/images/portfolio/nametag/onboarding-3.avif": {
    "width": 2880,
    "height": 1600
  },
  "/images/portfolio/nametag/profile-completion.avif": {
    "width": 3476,
    "height": 2226
  },
  "/images/portfolio/nametag/profile.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/nametag/space.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/nsw-cdp/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/nsw-cdp/analysis.avif": {
    "width": 3200,
    "height": 2000
  },
  "/images/portfolio/nsw-cdp/dataset-page.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/nsw-cdp/faceted-search.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/nsw-cdp/hero.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/nsw-cdp/nsw-cdp-bg.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/nsw-cdp/nsw-cdp-ui-desktop.avif": {
    "width": 2800,
    "height": 2000
  },
  "/images/portfolio/nsw-cdp/nsw-cdp-ui-mobile.avif": {
    "width": 640,
    "height": 1400
  },
  "/images/portfolio/nsw-cdp/reports.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/nsw-cdp/scale-download.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/nsw-cdp/testing-1.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/nsw-cdp/testing-2.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/nsw-cdp/testing-3.avif": {
    "width": 2400,
    "height": 2400
  },
  "/images/portfolio/nsw-cdp/testing-4.avif": {
    "width": 2400,
    "height": 2400
  },
  "/images/portfolio/nsw-cdp/testing-summary.avif": {
    "width": 3200,
    "height": 1744
  },
  "/images/portfolio/orpheus/_og.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/orpheus/cover.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/orpheus/design-system-overview.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/orpheus/inspiration-board.avif": {
    "width": 2880,
    "height": 1800
  },
  "/images/portfolio/orpheus/internationalisation.avif": {
    "width": 4800,
    "height": 3600
  },
  "/images/portfolio/orpheus/material-design.avif": {
    "width": 2880,
    "height": 1800
  },
  "/images/portfolio/orpheus/material-design.png": {
    "width": 2840,
    "height": 1760
  },
  "/images/portfolio/orpheus/red-monastery.avif": {
    "width": 3200,
    "height": 11320
  },
  "/images/portfolio/orpheus/storybook.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/orpheus/tripureshwor-aerial.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/orpheus/tripureshwor-gallery.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/orpheus/tripureshwor-interior.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/rankdat/rankdat-poster.avif": {
    "width": 2880,
    "height": 2160
  },
  "/images/portfolio/stylespin/stylespin-poster.avif": {
    "width": 2880,
    "height": 2160
  }
};

export function getImageDimensions(src: string): { width: number; height: number } | undefined {
  return imageDimensions[src];
}
