// Auto-generated by scripts/generate-image-dimensions.ts
// Run: pnpm tsx scripts/generate-image-dimensions.ts

export const imageDimensions: Record<string, { width: number; height: number }> = {
  "/images/portfolio/beyondwords/_beyondwords-cover.jpg": {
    "width": 1200,
    "height": 630
  },
  "/images/portfolio/beyondwords/articles.avif": {
    "width": 3200,
    "height": 6400
  },
  "/images/portfolio/beyondwords/beyondwords-ui.avif": {
    "width": 2884,
    "height": 1604
  },
  "/images/portfolio/beyondwords/dashboard.avif": {
    "width": 3200,
    "height": 6800
  },
  "/images/portfolio/beyondwords/home-page-concept.avif": {
    "width": 3200,
    "height": 19784
  },
  "/images/portfolio/beyondwords/onboarding-1.avif": {
    "width": 3200,
    "height": 7200
  },
  "/images/portfolio/beyondwords/onboarding-2.avif": {
    "width": 3200,
    "height": 7200
  },
  "/images/portfolio/beyondwords/plan-management.avif": {
    "width": 3200,
    "height": 6400
  },
  "/images/portfolio/beyondwords/security.avif": {
    "width": 3200,
    "height": 6400
  },
  "/images/portfolio/beyondwords/semantic-colours.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/beyondwords/ui-library-component-details.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/beyondwords/ui-library-usage.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/beyondwords/ui-library.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/booking-bg.avif": {
    "width": 2400,
    "height": 1599
  },
  "/images/portfolio/booking-ui-1.avif": {
    "width": 800,
    "height": 1750
  },
  "/images/portfolio/booking-ui-2.avif": {
    "width": 800,
    "height": 1750
  },
  "/images/portfolio/booking-ui-3.avif": {
    "width": 800,
    "height": 1750
  },
  "/images/portfolio/booking-ui-4.avif": {
    "width": 800,
    "height": 1750
  },
  "/images/portfolio/bookingcom-1.avif": {
    "width": 2400,
    "height": 1800
  },
  "/images/portfolio/bookingcom-2.avif": {
    "width": 3200,
    "height": 1800
  },
  "/images/portfolio/bookingcom-3.avif": {
    "width": 3926,
    "height": 2209
  },
  "/images/portfolio/bookingcom-4.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/brokerengine/5tHNIK8Ki1uZHAWwcz5rp7UUZ0.avif": {
    "width": 914,
    "height": 526
  },
  "/images/portfolio/brokerengine/SMgQI5vK5lC4IWjN22NksUlXY.avif": {
    "width": 1788,
    "height": 530
  },
  "/images/portfolio/brokerengine/WfRetAwxjBB59L3686NWp1wB7M.avif": {
    "width": 3476,
    "height": 2226
  },
  "/images/portfolio/brokerengine/_brokerengine-bg-poster.avif": {
    "width": 598,
    "height": 400
  },
  "/images/portfolio/brokerengine/_brokerengine-cover.jpg": {
    "width": 1600,
    "height": 840
  },
  "/images/portfolio/brokerengine/card-payment-system.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/brokerengine/comments.avif": {
    "width": 3476,
    "height": 2226
  },
  "/images/portfolio/brokerengine/compose-component.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/brokerengine/deal-after.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/brokerengine/deal-before.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/brokerengine/deals-after.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/brokerengine/deals-before.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/brokerengine/figma-files.avif": {
    "width": 6080,
    "height": 2116
  },
  "/images/portfolio/brokerengine/filter-after.avif": {
    "width": 3200,
    "height": 3704
  },
  "/images/portfolio/brokerengine/filter-before.avif": {
    "width": 3200,
    "height": 3704
  },
  "/images/portfolio/brokerengine/messaging.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/brokerengine/onboarding.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/brokerengine/pipeline.avif": {
    "width": 2880,
    "height": 1600
  },
  "/images/portfolio/brokerengine/responsive-contact.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/brokerengine/tasks.avif": {
    "width": 3200,
    "height": 1920
  },
  "/images/portfolio/donotstay-1.jpg": {
    "width": 2560,
    "height": 1914
  },
  "/images/portfolio/donotstay-poster.avif": {
    "width": 2880,
    "height": 2160
  },
  "/images/portfolio/gsq-bg.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/gsq-ui-desktop.avif": {
    "width": 2800,
    "height": 2000
  },
  "/images/portfolio/gsq-ui-modal.avif": {
    "width": 2720,
    "height": 1600
  },
  "/images/portfolio/nametag-1.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/nametag-2.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/nametag-3.avif": {
    "width": 3200,
    "height": 2400
  },
  "/images/portfolio/nsw-cdp-bg.avif": {
    "width": 3200,
    "height": 2132
  },
  "/images/portfolio/nsw-cdp-ui-desktop.avif": {
    "width": 2800,
    "height": 2000
  },
  "/images/portfolio/nsw-cdp-ui-mobile.avif": {
    "width": 640,
    "height": 1400
  },
  "/images/portfolio/rankdat-poster.avif": {
    "width": 2880,
    "height": 2160
  },
  "/images/portfolio/stylespin-poster.avif": {
    "width": 2880,
    "height": 2160
  }
};

export function getImageDimensions(src: string): { width: number; height: number } | undefined {
  return imageDimensions[src];
}
