import { readdirSync, readFileSync, statSync, writeFileSync, watch } from "fs";
import { join, relative } from "path";
import imageSize from "image-size";

const PUBLIC_DIR = join(process.cwd(), "public");
const PORTFOLIO_DIR = join(PUBLIC_DIR, "images/portfolio");
const OUTPUT_FILE = join(process.cwd(), "src/lib/image-dimensions.ts");

type Dimensions = { width: number; height: number };

function scanDirectory(dir: string, map: Record<string, Dimensions>) {
  const entries = readdirSync(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      scanDirectory(fullPath, map);
    } else if (/\.(avif|webp|png|jpg|jpeg|gif)$/i.test(entry)) {
      try {
        const buffer = readFileSync(fullPath);
        const result = imageSize(buffer);
        if (result.width && result.height) {
          const relativePath = "/" + relative(PUBLIC_DIR, fullPath);
          map[relativePath] = {
            width: result.width,
            height: result.height,
          };
        }
      } catch (err) {
        console.error(`Failed to read dimensions for ${fullPath}:`, err);
      }
    }
  }
}

function generate() {
  const dimensionsMap: Record<string, Dimensions> = {};
  console.log("Scanning portfolio images...");
  scanDirectory(PORTFOLIO_DIR, dimensionsMap);

  const output = `// Auto-generated by scripts/generate-image-dimensions.ts
// Run: pnpm tsx scripts/generate-image-dimensions.ts

export const imageDimensions: Record<string, { width: number; height: number }> = ${JSON.stringify(dimensionsMap, null, 2)};

export function getImageDimensions(src: string): { width: number; height: number } | undefined {
  return imageDimensions[src];
}
`;

  writeFileSync(OUTPUT_FILE, output);
  console.log(`Generated ${OUTPUT_FILE} with ${Object.keys(dimensionsMap).length} images.`);
}

// Initial run
generate();

// Watch mode: re-generate when images change
if (process.argv.includes("--watch")) {
  let timeout: ReturnType<typeof setTimeout> | null = null;

  watch(PORTFOLIO_DIR, { recursive: true }, (_event, filename) => {
    if (!filename || !/\.(avif|webp|png|jpg|jpeg|gif)$/i.test(filename)) return;
    if (timeout) clearTimeout(timeout);
    timeout = setTimeout(() => {
      console.log(`Image changed: ${filename}`);
      generate();
    }, 300);
  });

  console.log("Watching for image changes...");
}
